### ISSUE TITLE
Speech Slider

### ISSUE THREAD

**Issue by albert-schilling** [albert-schilling/ciceroic#27]
## Value Statement

As a **(novice/skilled) orator**
I can **browse speeches filtered by category, evaluations and date**
in order to **find the speech I am most interested in**.

## Description (Text, Scribble, Wireframe, Design)

- The start screen shows several speech sliders filtering the speech according to different attributes like category, date or number of evaluations.
- [Inspiration from TED Talks Website ](https://user-images.githubusercontent.com/59568178/81583647-ef35db00-93b1-11ea-9a61-0bf6fbed2c9c.png)

## Acceptance Criteria

- [x] The start screen shows several sliders according to at least the following attributes: categories (humor, comedy, pitch, educational), date, number of evaluations.
- [x] The slider is responsive and shows as many speeches as fit.
- [x] Further speeches can be displayed by clicking a left or right arrow to slide through the speeches.
- [x] Clicking a speech, opens the speech's detail page.

## Tasks

- [x] Create necessary components
- [x] Styling for mobile and desktop view
- [ ] Write unit and e2e tests

## Size

Large
